import type { MdiIcon } from '../contract/entities.ts';

const ICONS: Readonly<Record<string, MdiIcon>> = {
  Basics: 'mdi:card-text-outline',
  Sensors: 'mdi:thermometer',
  Lights: 'mdi:lightbulb-group',
  Climate: 'mdi:thermostat',
  Devices: 'mdi:devices',
  Media: 'mdi:speaker',
  Energy: 'mdi:flash',
  Problems: 'mdi:alert-circle-outline',
  Fuel: 'mdi:gas-station',
  Status: 'mdi:information-outline',
  Locks: 'mdi:lock',
  Openings: 'mdi:car-door',
  Tyres: 'mdi:tire',
  Power: 'mdi:power-plug',
  Load: 'mdi:gauge',
  Storage: 'mdi:harddisk',
  Guests: 'mdi:server',
  Health: 'mdi:heart-pulse',
  Thresholds: 'mdi:tune-vertical',
  'Wi-Fi': 'mdi:wifi',
  VPN: 'mdi:vpn',
  Traffic: 'mdi:swap-vertical',
  Updates: 'mdi:update',
  Scenes: 'mdi:palette',
  More: 'mdi:dots-horizontal',
  Entity: 'mdi:shape-outline',
  Look: 'mdi:palette-outline',
  Colour: 'mdi:palette-outline',
  State: 'mdi:text-short',
  Controls: 'mdi:gesture-tap-button',
  Subject: 'mdi:tag-outline',
  Heading: 'mdi:format-title',
  Rows: 'mdi:format-list-bulleted',
  'Order and summary': 'mdi:sort',
  Calendars: 'mdi:calendar',
  Messages: 'mdi:message-text-outline',
  Sources: 'mdi:source-branch',
  Clients: 'mdi:devices',
  Networks: 'mdi:lan',
  Button: 'mdi:gesture-tap',
  Chips: 'mdi:chip',
  Item: 'mdi:card-outline',
  Player: 'mdi:play-circle-outline',
  'More entities': 'mdi:playlist-plus',
};

export function iconFor(title: string): MdiIcon {
  return ICONS[title] ?? 'mdi:tune';
}
