import { defineConfig } from 'oxlint';

export default defineConfig({
  options: {
    denyWarnings: true,
    reportUnusedDisableDirectives: 'error',
    typeAware: true,
    typeCheck: true,
  },
  plugins: ['typescript', 'import', 'unicorn', 'oxc', 'node'],
  rules: {
    curly: 'error',
    'default-param-last': 'error',
    'guard-for-in': 'error',
    'import/consistent-type-specifier-style': 'error',
    'import/first': 'error',
    'import/no-commonjs': 'error',
    'import/no-cycle': 'error',
    'import/no-duplicates': 'error',
    'import/no-mutable-exports': 'error',
    'import/no-namespace': 'error',
    'import/no-self-import': 'error',
    'no-await-in-loop': 'error',
    'no-console': 'error',
    'no-else-return': 'error',
    'no-eq-null': 'error',
    'no-loop-func': 'error',
    'no-multi-assign': 'error',
    'no-param-reassign': 'error',
    'no-return-assign': 'error',
    'no-unneeded-ternary': 'error',
    'no-useless-computed-key': 'error',
    'no-useless-return': 'error',
    'no-var': 'error',
    'node/no-process-env': 'error',
    'object-shorthand': 'error',
    'operator-assignment': 'error',
    'oxc/no-accumulating-spread': 'error',
    'oxc/no-barrel-file': 'error',
    'oxc/no-map-spread': 'error',
    'prefer-const': 'error',
    'prefer-object-has-own': 'error',
    'prefer-object-spread': 'error',
    'prefer-template': 'error',
    'symbol-description': 'error',
    'typescript/array-type': 'error',
    'typescript/ban-ts-comment': 'error',
    'typescript/consistent-generic-constructors': 'error',
    'typescript/consistent-indexed-object-style': 'error',
    'typescript/consistent-type-assertions': 'error',
    'typescript/consistent-type-definitions': 'error',
    'typescript/consistent-type-exports': 'error',
    'typescript/consistent-type-imports': 'error',
    'typescript/no-deprecated': 'error',
    'typescript/no-explicit-any': 'error',
    'typescript/no-inferrable-types': 'error',
    'typescript/no-namespace': 'error',
    'typescript/no-unnecessary-template-expression': 'error',
    'typescript/no-unnecessary-type-conversion': 'error',
    'typescript/prefer-find': 'error',
    'typescript/prefer-for-of': 'error',
    'typescript/prefer-reduce-type-parameter': 'error',
    'typescript/prefer-regexp-exec': 'error',
    'typescript/restrict-plus-operands': 'error',
    'typescript/unified-signatures': 'error',
    'unicorn/catch-error-name': 'error',
    'unicorn/consistent-function-scoping': 'error',
    'unicorn/error-message': 'error',
    'unicorn/explicit-length-check': 'error',
    'unicorn/filename-case': 'error',
    'unicorn/no-array-for-each': 'error',
    'unicorn/no-lonely-if': 'error',
    'unicorn/prefer-array-flat-map': 'error',
    'unicorn/prefer-array-some': 'error',
    'unicorn/prefer-math-min-max': 'error',
    'unicorn/prefer-node-protocol': 'error',
    'unicorn/prefer-optional-catch-binding': 'error',
    'unicorn/prefer-regexp-test': 'error',
    'unicorn/prefer-set-has': 'error',
    'unicorn/prefer-spread': 'error',
    'unicorn/prefer-string-replace-all': 'error',
    'unicorn/prefer-string-slice': 'error',
    'unicorn/prefer-string-trim-start-end': 'error',
    'unicorn/prefer-structured-clone': 'error',
    'unicorn/require-number-to-fixed-digits-argument': 'error',
    'unicorn/throw-new-error': 'error',
    yoda: 'error',
  },
  overrides: [
    {
      files: ['src/*/main.ts', 'demo/main.ts', 'demo/entities.ts', 'tools/*.ts'],
      rules: { 'no-console': 'off', 'no-await-in-loop': 'off' },
    },
    {
      files: [
        'src/cards/parts/popup-registry.ts',
        'src/cards/parts/popup-registry.test.ts',
        'src/store/store.ts',
        'src/store/store.test.ts',
        'src/store/shipped.ts',
        'src/store/shipped.test.ts',
        'src/cards/template-failure.test.ts',
        'src/editors/template-card-failure.test.ts',
      ],
      rules: { 'no-console': 'off' },
    },
  ],
});
