import type { InputBooleanId, WeatherId } from '../src/contract/entities.ts';
import type { Car, Guest, Home, Person, Room, System } from '../src/home/types.ts';

const OUTSIDE: WeatherId = 'weather.demo_weather_south';

const VACATION: InputBooleanId = 'input_boolean.infrastructure_vacation';

const HOME_ASSISTANT: Guest = {
  host: 'ha.home.arpa',
  status: 'binary_sensor.infrastructure_home_assistant_status',
  cpu: 'sensor.infrastructure_home_assistant_cpu_usage',
  memory: 'sensor.infrastructure_home_assistant_memory_used',
};

const SYSTEM: System = {
  cpu: HOME_ASSISTANT.cpu,
  memory: HOME_ASSISTANT.memory,
  diskFree: 'sensor.infrastructure_home_assistant_host_disk_free',
  diskUsed: 'sensor.infrastructure_home_assistant_host_disk_used',
  services: [
    'binary_sensor.infrastructure_matter_server',
    'binary_sensor.infrastructure_openthread_border_router',
  ],
  updates: [
    'update.infrastructure_home_assistant_core_update',
    'update.infrastructure_home_assistant_operating_system_update',
    'update.infrastructure_home_assistant_supervisor_update',
    'update.infrastructure_advanced_ssh_web_terminal_update',
    'update.infrastructure_file_editor_update',
    'update.infrastructure_let_s_encrypt_update',
    'update.infrastructure_matter_server_update',
    'update.infrastructure_openthread_border_router_update',
    'update.infrastructure_roborock_local_server_beta_update',
    'update.infrastructure_better_thermostat_update',
    'update.infrastructure_car_data_update',
    'update.infrastructure_hacs_update',
    'update.infrastructure_mitsubishi_air_conditioner_update',
  ],
  firmware: [
    'update.infrastructure_home_assistant_connect_zbt_2_firmware',
    'update.infrastructure_server_outlet_firmware',
  ],
  proxmox: {
    outlet: {
      entity: 'switch.infrastructure_server_outlet',
      energy: {
        power: 'sensor.infrastructure_server_outlet_power',
        today: 'sensor.infrastructure_server_outlet_energy_daily',
        total: 'sensor.infrastructure_server_outlet_energy',
      },
    },
    cpu: 'sensor.infrastructure_server_cpu_usage',
    memory: 'sensor.infrastructure_server_memory_used',
    lastBoot: 'sensor.infrastructure_server_last_boot',
    uplink: 'sensor.infrastructure_router_server_link_speed',
    temperatures: {
      cpu: 'sensor.infrastructure_server_cpu_temperature',
      rootDisk: 'sensor.infrastructure_server_root_disk_temperature',
    },
    storage: [
      'sensor.infrastructure_local_storage_used',
      'sensor.infrastructure_local_zfs_storage_used',
      'sensor.infrastructure_storage_used',
      'sensor.infrastructure_offsite_storage_used',
    ],
    disks: {
      pool: 'sensor.infrastructure_server_pool_health',
      failing: 'sensor.infrastructure_server_disks_failing',
      lifeLeft: 'sensor.infrastructure_server_disk_life_left',
    },
    guests: [
      {
        host: 'dns.home.arpa',
        status: 'binary_sensor.infrastructure_dns_status',
        cpu: 'sensor.infrastructure_dns_cpu_usage',
        memory: 'sensor.infrastructure_dns_memory_used',
        disk: {
          used: 'sensor.infrastructure_dns_disk_usage',
          size: 'sensor.infrastructure_dns_max_disk_usage',
        },
      },
      HOME_ASSISTANT,
      {
        host: 'media.home.arpa',
        status: 'binary_sensor.infrastructure_media_status',
        cpu: 'sensor.infrastructure_media_cpu_usage',
        memory: 'sensor.infrastructure_media_memory_used',
        disk: {
          used: 'sensor.infrastructure_media_disk_usage',
          size: 'sensor.infrastructure_media_max_disk_usage',
        },
      },
      {
        host: 'arr.home.arpa',
        status: 'binary_sensor.infrastructure_arr_status',
        cpu: 'sensor.infrastructure_arr_cpu_usage',
        memory: 'sensor.infrastructure_arr_memory_used',
        disk: {
          used: 'sensor.infrastructure_arr_disk_usage',
          size: 'sensor.infrastructure_arr_max_disk_usage',
        },
      },
      {
        host: 'docs.home.arpa',
        status: 'binary_sensor.infrastructure_docs_status',
        cpu: 'sensor.infrastructure_docs_cpu_usage',
        memory: 'sensor.infrastructure_docs_memory_used',
        disk: {
          used: 'sensor.infrastructure_docs_disk_usage',
          size: 'sensor.infrastructure_docs_max_disk_usage',
        },
      },
      {
        host: 'router.vpn.home.arpa',
        status: 'binary_sensor.infrastructure_vpn_router_status',
        cpu: 'sensor.infrastructure_vpn_router_cpu_usage',
        memory: 'sensor.infrastructure_vpn_router_memory_used',
      },
      {
        host: 'exit.vpn.home.arpa',
        status: 'binary_sensor.infrastructure_vpn_exit_node_status',
        cpu: 'sensor.infrastructure_vpn_exit_node_cpu_usage',
        memory: 'sensor.infrastructure_vpn_exit_node_memory_used',
      },
      {
        host: 'downloads.home.arpa',
        status: 'binary_sensor.infrastructure_downloads_status',
        cpu: 'sensor.infrastructure_downloads_cpu_usage',
        memory: 'sensor.infrastructure_downloads_memory_used',
        disk: {
          used: 'sensor.infrastructure_downloads_disk_usage',
          size: 'sensor.infrastructure_downloads_max_disk_usage',
        },
      },
    ],
    backups: {
      last: 'sensor.infrastructure_server_last_backup',
      problem: 'binary_sensor.infrastructure_server_backup_status',
      bucket: 'sensor.infrastructure_server_bucket_used',
    },
    checks: {
      failed: 'sensor.infrastructure_server_checks_failed',
      lastRun: 'sensor.infrastructure_server_checks_last_run',
      overdue: 'binary_sensor.infrastructure_server_checks_overdue',
    },
    notifications: {
      messages: 'sensor.infrastructure_proxmox_notifications',
      clear: 'script.infrastructure_clear_proxmox_notifications',
      sources: [
        { source: 'pve', name: 'Proxmox VE' },
        { source: 'pbs', name: 'PBS' },
      ],
    },
  },
  adguard: {
    protection: 'switch.infrastructure_adguard_home_protection',
    queries: 'sensor.infrastructure_adguard_home_queries',
    blocked: 'sensor.infrastructure_adguard_home_blocked',
    ratio: 'sensor.infrastructure_adguard_home_blocked_share',
    speed: 'sensor.infrastructure_adguard_home_processing_time',
    rules: 'sensor.infrastructure_adguard_home_rules_count',
    update: 'update.infrastructure_adguard_home',
  },
  network: {
    latency: ['sensor.infrastructure_router_cloudflare', 'sensor.infrastructure_router_google'],
    wan: 'sensor.infrastructure_router_isp_link_speed',
    devices: [
      'sensor.infrastructure_router_state',
      'sensor.infrastructure_switch_1_state',
      'sensor.infrastructure_switch_2_state',
      'sensor.infrastructure_ap_state',
    ],
    wifi: [
      {
        key: 'users',
        enabled: 'switch.infrastructure_home_users_enabled',
        qr: 'image.infrastructure_home_users_qr_code',
      },
      {
        key: 'iot',
        enabled: 'switch.infrastructure_home_iot_enabled',
        qr: 'image.infrastructure_home_iot_qr_code',
      },
      {
        key: 'media',
        enabled: 'switch.infrastructure_home_media_enabled',
        qr: 'image.infrastructure_home_media_qr_code',
      },
      {
        key: 'guests',
        enabled: 'switch.infrastructure_home_guests_enabled',
        qr: 'image.infrastructure_home_guests_qr_code',
        switchable: true,
      },
    ],
    vpn: [
      'binary_sensor.infrastructure_tailscale_router_connected_to_control',
      'binary_sensor.infrastructure_tailscale_exit_node_connected_to_control',
    ],
    clients: {
      entity: 'sensor.infrastructure_unifi_clients',
      names: 'sensor.infrastructure_adguard_clients',
      networks: [
        { name: 'Users', icon: 'mdi:account-multiple', subnet: '10.1.0.0/16' },
        { name: 'IoT', icon: 'mdi:home-automation', subnet: '10.3.0.0/16' },
        { name: 'Media', icon: 'mdi:television-play', subnet: '10.4.0.0/16' },
        { name: 'Servers', icon: 'mdi:server', subnet: '10.5.0.0/16' },
        { name: 'VPN', icon: 'mdi:vpn', subnet: '10.6.0.0/16' },
        { name: 'DMZ', icon: 'mdi:shield-half-full', subnet: '10.7.0.0/16' },
        { name: 'Management', icon: 'mdi:cog-outline', subnet: '10.9.0.0/16' },
        { name: 'Guests', icon: 'mdi:account-question-outline', subnet: '10.2.0.0/16' },
      ],
    },
    router: {
      cpu: 'sensor.infrastructure_router_cpu_usage',
      temperature: 'sensor.infrastructure_router_cpu_temperature',
    },
    firmware: [
      'update.infrastructure_router_firmware',
      'update.infrastructure_switch_1_firmware',
      'update.infrastructure_switch_2_firmware',
      'update.infrastructure_ap_firmware',
    ],
  },
  media: {
    streams: 'sensor.infrastructure_plex',
    update: 'update.infrastructure_plex_update',
    requests: {
      pending: 'sensor.infrastructure_seerr_pending_requests',
      processing: 'sensor.infrastructure_seerr_processing_requests',
    },
    movies: {
      queue: 'sensor.infrastructure_radarr_queue',
      count: 'sensor.infrastructure_radarr_movies',
      health: 'binary_sensor.infrastructure_radarr_health',
      space: 'sensor.infrastructure_radarr_free_space',
      calendar: 'calendar.calendar_1',
    },
    shows: {
      queue: 'sensor.infrastructure_sonarr_queue',
      count: 'sensor.infrastructure_sonarr_shows',
      wanted: 'sensor.infrastructure_sonarr_wanted',
      upcoming: 'sensor.infrastructure_sonarr_upcoming',
      calendar: 'calendar.calendar_2',
    },
  },
};

const PEOPLE: readonly Person[] = [
  {
    key: 'joe',
    entity: 'person.joe',
    health: {
      steps: 'sensor.joe_phone_steps',
      distance: 'sensor.joe_phone_distance',
      flightsClimbed: 'sensor.joe_phone_flights_climbed',
      activeEnergy: 'sensor.joe_phone_active_energy',
      restingEnergy: 'sensor.joe_phone_resting_energy',
    },
    devices: [
      {
        key: 'phone',
        name: 'Phone',
        icon: 'mdi:cellphone',
        tracker: 'device_tracker.joe_phone',
        battery: 'sensor.joe_phone_battery_level',
        batteryState: 'sensor.joe_phone_battery_state',
        connection: 'sensor.joe_phone_connection',
        network: 'sensor.joe_phone_network',
        storage: 'sensor.joe_phone_storage',
        focus: 'binary_sensor.joe_phone_focus',
        focusName: 'sensor.joe_phone_focus_name',
        activity: 'sensor.joe_phone_activity',
        permission: 'sensor.joe_phone_location_access',
      },
      {
        key: 'tablet',
        name: 'Tablet',
        icon: 'mdi:tablet',
        tracker: 'device_tracker.joe_tablet',
        battery: 'sensor.joe_tablet_battery_level',
        batteryState: 'sensor.joe_tablet_battery_state',
        connection: 'sensor.joe_tablet_connection',
        network: 'sensor.joe_tablet_network',
        storage: 'sensor.joe_tablet_storage',
        focus: 'binary_sensor.joe_tablet_focus',
        focusName: 'sensor.joe_tablet_focus_name',
        activity: 'sensor.joe_tablet_activity',
        permission: 'sensor.joe_tablet_location_access',
      },
    ],
  },
  {
    key: 'jane',
    entity: 'person.jane',
    health: {
      steps: 'sensor.jane_phone_steps',
      distance: 'sensor.jane_phone_distance',
      flightsClimbed: 'sensor.jane_phone_flights_climbed',
      activeEnergy: 'sensor.jane_phone_active_energy',
      restingEnergy: 'sensor.jane_phone_resting_energy',
    },
    devices: [
      {
        key: 'phone',
        name: 'Phone',
        icon: 'mdi:cellphone',
        tracker: 'device_tracker.jane_phone',
        battery: 'sensor.jane_phone_battery_level',
        batteryState: 'sensor.jane_phone_battery_state',
        connection: 'sensor.jane_phone_connection',
        network: 'sensor.jane_phone_network',
        storage: 'sensor.jane_phone_storage',
        focus: 'binary_sensor.jane_phone_focus',
        focusName: 'sensor.jane_phone_focus_name',
        activity: 'sensor.jane_phone_activity',
        permission: 'sensor.jane_phone_location_access',
      },
    ],
  },
];

const SECTION_TITLES = {
  rooms: 'Rooms',
  people: 'People',
  garage: 'Garage',
  infrastructure: 'Infrastructure',
} as const;

const ROOMS: readonly Room[] = [
  {
    key: 'bathroom',
    name: 'Bathroom',
    icon: 'mdi:shower',
    temperature: 'sensor.bathroom_climate_temperature',
    humidity: 'sensor.bathroom_climate_humidity',
    lights: {
      group: 'light.bathroom_lights',
      members: ['light.bathroom_top'],
      scenes: [
        'scene.bathroom_lights_concentrate',
        'scene.bathroom_lights_energize',
        'scene.bathroom_lights_natural_light',
        'scene.bathroom_lights_nightlight',
        'scene.bathroom_lights_read',
        'scene.bathroom_lights_relax',
        'scene.bathroom_lights_rest',
      ],
      activeScene: 'select.bathroom_lights_scene',
    },
    heating: {
      entity: 'climate.bathroom_heating',
      preset: true,
      thermostats: [
        {
          valve: 'sensor.bathroom_thermostat_valve_position',
          battery: 'sensor.bathroom_thermostat_battery',
        },
      ],
    },
    batteries: ['sensor.bathroom_climate_battery', 'sensor.bathroom_switch_battery'],
    firmware: ['update.bathroom_climate_firmware', 'update.bathroom_thermostat_firmware'],
  },
  {
    key: 'bedroom',
    name: 'Bedroom',
    icon: 'mdi:bed-king',
    temperature: 'sensor.bedroom_climate_temperature',
    humidity: 'sensor.bedroom_climate_humidity',
    window: 'binary_sensor.bedroom_window',
    lights: {
      group: 'light.bedroom_lights',
      color: true,
      members: [
        {
          group: 'light.bedroom_top',
          members: ['light.bedroom_top_1', 'light.bedroom_top_2', 'light.bedroom_top_3'],
        },
      ],
      scenes: [
        'scene.bedroom_lights_adrift',
        'scene.bedroom_lights_arctic_aurora',
        'scene.bedroom_lights_chinatown',
        'scene.bedroom_lights_concentrate',
        'scene.bedroom_lights_disturbia',
        'scene.bedroom_lights_emerald_flutter',
        'scene.bedroom_lights_energize',
        'scene.bedroom_lights_galaxy',
        'scene.bedroom_lights_lake_placid',
        'scene.bedroom_lights_motown',
        'scene.bedroom_lights_natural_light',
        'scene.bedroom_lights_nebula',
        'scene.bedroom_lights_nightlight',
        'scene.bedroom_lights_osaka',
        'scene.bedroom_lights_read',
        'scene.bedroom_lights_relax',
        'scene.bedroom_lights_rest',
        'scene.bedroom_lights_soho',
        'scene.bedroom_lights_tokyo',
      ],
      activeScene: 'select.bedroom_lights_scene',
    },
    heating: {
      entity: 'climate.bedroom_heating',
      preset: true,
      thermostats: [
        {
          valve: 'sensor.bedroom_thermostat_1_valve_position',
          battery: 'sensor.bedroom_thermostat_1_battery',
        },
        {
          valve: 'sensor.bedroom_thermostat_2_valve_position',
          battery: 'sensor.bedroom_thermostat_2_battery',
        },
      ],
    },
    ac: {
      entity: 'climate.ecobee',
      fan: true,
      swing: true,
      powerSaving: 'select.bedroom_ac_power_saving_mode',
      dehumidifier: 'number.bedroom_ac_dehumidifier_level',
      energy: {
        power: 'sensor.bedroom_ac_power',
        today: 'sensor.bedroom_ac_energy_daily',
        total: 'sensor.bedroom_ac_energy',
      },
    },
    media: ['media_player.bedroom'],
    batteries: [
      'sensor.bedroom_climate_battery',
      'sensor.bedroom_switch_battery',
      'sensor.bedroom_window_battery',
    ],
    firmware: [
      'update.bedroom_climate_firmware',
      'update.bedroom_thermostat_1_firmware',
      'update.bedroom_thermostat_2_firmware',
      'update.bedroom_window_firmware',
    ],
  },
  {
    key: 'dressing',
    name: 'Dressing',
    icon: 'mdi:wardrobe',
    temperature: 'sensor.dressing_climate_temperature',
    humidity: 'sensor.dressing_climate_humidity',
    lights: {
      group: 'light.dressing_lights',
      members: [
        {
          group: 'light.dressing_top',
          members: [
            'light.dressing_top_1',
            'light.dressing_top_2',
            'light.dressing_top_3',
            'light.dressing_top_4',
          ],
        },
      ],
      scenes: [
        'scene.dressing_lights_concentrate',
        'scene.dressing_lights_energize',
        'scene.dressing_lights_natural_light',
        'scene.dressing_lights_nightlight',
        'scene.dressing_lights_read',
        'scene.dressing_lights_relax',
        'scene.dressing_lights_rest',
      ],
      activeScene: 'select.dressing_lights_scene',
    },
    batteries: ['sensor.dressing_climate_battery', 'sensor.dressing_switch_battery'],
    firmware: ['update.dressing_climate_firmware'],
  },
  {
    key: 'entry',
    name: 'Entry',
    icon: 'mdi:door',
    temperature: 'sensor.entry_climate_temperature',
    humidity: 'sensor.entry_climate_humidity',
    door: 'binary_sensor.entry_door',
    lock: 'lock.front_door',
    lights: {
      group: 'light.entry_lights',
      color: true,
      members: [
        {
          group: 'light.entry_top',
          members: ['light.entry_top_1', 'light.entry_top_2', 'light.entry_top_3'],
        },
      ],
      scenes: [
        'scene.entry_lights_adrift',
        'scene.entry_lights_arctic_aurora',
        'scene.entry_lights_chinatown',
        'scene.entry_lights_concentrate',
        'scene.entry_lights_disturbia',
        'scene.entry_lights_emerald_flutter',
        'scene.entry_lights_energize',
        'scene.entry_lights_lake_placid',
        'scene.entry_lights_motown',
        'scene.entry_lights_natural_light',
        'scene.entry_lights_nebula',
        'scene.entry_lights_nightlight',
        'scene.entry_lights_osaka',
        'scene.entry_lights_read',
        'scene.entry_lights_relax',
        'scene.entry_lights_rest',
        'scene.entry_lights_soho',
        'scene.entry_lights_tokyo',
      ],
      activeScene: 'select.entry_lights_scene',
    },
    ac: {
      entity: 'climate.hvac',
      fan: true,
      swing: true,
      horizontalSwing: true,
      powerSaving: 'select.entry_ac_power_saving_mode',
      dehumidifier: 'number.entry_ac_dehumidifier_level',
      energy: {
        power: 'sensor.entry_ac_power',
        today: 'sensor.entry_ac_energy_daily',
        total: 'sensor.entry_ac_energy',
      },
    },
    batteries: [
      'sensor.entry_climate_battery',
      'sensor.entry_door_battery',
      'sensor.entry_door_lock_battery',
      'sensor.entry_switch_1_battery',
      'sensor.entry_switch_2_battery',
    ],
    firmware: ['update.entry_climate_firmware', 'update.entry_door_firmware'],
  },
  {
    key: 'hall',
    name: 'Hall',
    icon: 'mdi:washing-machine',
    temperature: 'sensor.hall_climate_temperature',
    humidity: 'sensor.hall_climate_humidity',
    lights: {
      group: 'light.hall_lights',
      members: [
        {
          group: 'light.hall_top',
          members: [
            'light.hall_top_1',
            'light.hall_top_2',
            'light.hall_top_3',
            'light.hall_top_4',
            'light.hall_top_5',
            'light.hall_top_6',
          ],
        },
      ],
      scenes: [
        'scene.hall_lights_concentrate',
        'scene.hall_lights_energize',
        'scene.hall_lights_natural_light',
        'scene.hall_lights_nightlight',
        'scene.hall_lights_read',
        'scene.hall_lights_relax',
        'scene.hall_lights_rest',
      ],
      activeScene: 'select.hall_lights_scene',
    },
    batteries: [
      'sensor.hall_climate_battery',
      'sensor.hall_laundry_water_leak_battery',
      'sensor.hall_switch_battery',
    ],
    leaks: ['binary_sensor.hall_laundry_water_leak'],
    firmware: ['update.hall_climate_firmware', 'update.hall_laundry_water_leak_firmware'],
  },
  {
    key: 'kitchen',
    name: 'Kitchen',
    icon: 'mdi:countertop',
    temperature: 'sensor.kitchen_climate_temperature',
    humidity: 'sensor.kitchen_climate_humidity',
    window: 'binary_sensor.kitchen_window',
    lights: {
      group: 'light.kitchen_lights',
      color: true,
      members: [
        'light.kitchen_countertop',
        {
          group: 'light.kitchen_top',
          members: ['light.kitchen_top_1', 'light.kitchen_top_2', 'light.kitchen_top_3'],
        },
      ],
      scenes: [
        'scene.kitchen_lights_adrift',
        'scene.kitchen_lights_arctic_aurora',
        'scene.kitchen_lights_chinatown',
        'scene.kitchen_lights_concentrate',
        'scene.kitchen_lights_disturbia',
        'scene.kitchen_lights_emerald_flutter',
        'scene.kitchen_lights_energize',
        'scene.kitchen_lights_lake_placid',
        'scene.kitchen_lights_motown',
        'scene.kitchen_lights_natural_light',
        'scene.kitchen_lights_nebula',
        'scene.kitchen_lights_nightlight',
        'scene.kitchen_lights_osaka',
        'scene.kitchen_lights_read',
        'scene.kitchen_lights_relax',
        'scene.kitchen_lights_rest',
        'scene.kitchen_lights_soho',
        'scene.kitchen_lights_tokyo',
      ],
      activeScene: 'select.kitchen_lights_scene',
    },
    heating: {
      entity: 'climate.kitchen_heating',
      preset: true,
      thermostats: [
        {
          valve: 'sensor.kitchen_thermostat_valve_position',
          battery: 'sensor.kitchen_thermostat_battery',
        },
      ],
    },
    outlets: [
      {
        entity: 'switch.kitchen_coffee_machine_outlet',
        energy: {
          power: 'sensor.kitchen_coffee_machine_outlet_power',
          today: 'sensor.kitchen_coffee_machine_outlet_energy_daily',
          total: 'sensor.kitchen_coffee_machine_outlet_energy',
        },
      },
      {
        entity: 'switch.kitchen_extractor_outlet',
        energy: {
          power: 'sensor.kitchen_extractor_outlet_power',
          today: 'sensor.kitchen_extractor_outlet_energy_daily',
          total: 'sensor.kitchen_extractor_outlet_energy',
        },
      },
    ],
    batteries: [
      'sensor.kitchen_climate_battery',
      'sensor.kitchen_coffee_machine_button_battery',
      'sensor.kitchen_button_battery',
      'sensor.kitchen_entry_button_battery',
      'sensor.kitchen_living_button_battery',
      'sensor.kitchen_window_battery',
    ],
    firmware: [
      'update.kitchen_climate_firmware',
      'update.kitchen_coffee_machine_outlet_firmware',
      'update.kitchen_extractor_outlet_firmware',
      'update.kitchen_thermostat_firmware',
      'update.kitchen_window_firmware',
    ],
  },
  {
    key: 'living',
    name: 'Living',
    icon: 'mdi:sofa',
    temperature: 'sensor.living_climate_temperature',
    humidity: 'sensor.living_climate_humidity',
    window: 'binary_sensor.living_window',
    lights: {
      group: 'light.living_lights',
      color: true,
      members: [
        {
          group: 'light.living_top',
          members: [
            'light.living_top_1',
            'light.living_top_2',
            'light.living_top_3',
            'light.living_top_4',
            'light.living_top_5',
            'light.living_top_6',
          ],
        },
        {
          group: 'light.living_tv',
          members: ['light.living_tv_left', 'light.living_tv_right'],
        },
      ],
      scenes: [
        'scene.living_lights_adrift',
        'scene.living_lights_arctic_aurora',
        'scene.living_lights_chinatown',
        'scene.living_lights_concentrate',
        'scene.living_lights_disturbia',
        'scene.living_lights_emerald_flutter',
        'scene.living_lights_energize',
        'scene.living_lights_lake_placid',
        'scene.living_lights_motown',
        'scene.living_lights_natural_light',
        'scene.living_lights_nebula',
        'scene.living_lights_nightlight',
        'scene.living_lights_osaka',
        'scene.living_lights_read',
        'scene.living_lights_relax',
        'scene.living_lights_rest',
        'scene.living_lights_soho',
        'scene.living_lights_tokyo',
      ],
      activeScene: 'select.living_lights_scene',
    },
    heating: {
      entity: 'climate.living_heating',
      preset: true,
      thermostats: [
        {
          valve: 'sensor.living_thermostat_1_valve_position',
          battery: 'sensor.living_thermostat_1_battery',
        },
        {
          valve: 'sensor.living_thermostat_2_valve_position',
          battery: 'sensor.living_thermostat_2_battery',
        },
      ],
    },
    vacuum: {
      entity: 'vacuum.demo_vacuum_0_ground_floor',
      status: 'sensor.living_vacuum_status',
      error: 'sensor.living_vacuum_error',
      battery: 'sensor.living_vacuum_battery',
      currentRoom: 'sensor.living_vacuum_current_room',
      progress: 'sensor.living_vacuum_cleaning_progress',
      area: 'sensor.living_vacuum_cleaning_area',
      time: 'sensor.living_vacuum_cleaning_time',
      lastClean: 'sensor.living_vacuum_last_clean_end',
      mopAttached: 'binary_sensor.living_vacuum_mop_attached',
      waterBoxAttached: 'binary_sensor.living_vacuum_water_box_attached',
      totals: {
        count: 'sensor.living_vacuum_cleaning_count',
        area: 'sensor.living_vacuum_cleaning_area_total',
        time: 'sensor.living_vacuum_cleaning_time_total',
      },
      map: 'image.living_vacuum_home',
      routines: [
        'button.living_vacuum_open_space_daily',
        'button.living_vacuum_office_daily',
        'button.living_vacuum_personal_daily',
        'button.living_vacuum_open_space_weekly',
        'button.living_vacuum_office_weekly',
        'button.living_vacuum_personal_weekly',
      ],
      settings: [
        'select.living_vacuum_cleaning_mode',
        'select.living_vacuum_mop_mode',
        'select.living_vacuum_mop_intensity',
      ],
      consumables: [
        {
          entity: 'sensor.living_vacuum_air_filter_time_left',
          reset: 'button.living_vacuum_reset_air_filter',
        },
        {
          entity: 'sensor.living_vacuum_main_brush_time_left',
          reset: 'button.living_vacuum_reset_main_brush',
        },
        {
          entity: 'sensor.living_vacuum_side_brush_time_left',
          reset: 'button.living_vacuum_reset_side_brush',
        },
        {
          entity: 'sensor.living_vacuum_sensor_time_left',
          reset: 'button.living_vacuum_reset_sensor',
        },
      ],
      warnings: ['binary_sensor.living_vacuum_water_shortage'],
      dock: {
        error: 'sensor.living_vacuum_dock_error',
        dustEmptying: 'switch.living_vacuum_dock_dust_emptying',
        mopDrying: 'switch.living_vacuum_dock_mop_drying',
        mopDryingTimeLeft: 'sensor.living_vacuum_dock_mop_drying_time_left',
        mopWashing: 'switch.living_vacuum_dock_mop_washing',
        consumables: [
          {
            entity: 'sensor.living_vacuum_dock_strainer_time_left',
            reset: 'button.living_vacuum_dock_reset_strainer',
          },
        ],
        warnings: [
          'binary_sensor.living_vacuum_dock_clean_water_box',
          'binary_sensor.living_vacuum_dock_dirty_water_box',
        ],
      },
    },
    media: [
      'media_player.lounge_room',
      {
        key: 'sonos',
        entity: 'media_player.living_room',
        bass: 'number.living_sonos_bass',
        treble: 'number.living_sonos_treble',
        balance: 'number.living_sonos_balance',
        loudness: 'switch.living_sonos_loudness',
        tv: {
          inputFormat: 'sensor.living_sonos_audio_input_format',
          nightSound: 'switch.living_sonos_night_sound',
          speechEnhancement: 'switch.living_sonos_speech_enhancement',
          audioDelay: 'number.living_sonos_audio_delay',
        },
        subwoofer: {
          enabled: 'switch.living_sonos_subwoofer_enabled',
          gain: 'number.living_sonos_sub_gain',
        },
        surround: {
          enabled: 'switch.living_sonos_surround_enabled',
          level: 'number.living_sonos_surround_level',
          musicLevel: 'number.living_sonos_music_surround_level',
          musicFullVolume: 'switch.living_sonos_surround_music_full_volume',
        },
      },
    ],
    batteries: ['sensor.living_climate_battery', 'sensor.living_window_battery'],
    firmware: [
      'update.living_climate_firmware',
      'update.living_thermostat_1_firmware',
      'update.living_thermostat_2_firmware',
      'update.living_window_firmware',
    ],
  },
  {
    key: 'office',
    name: 'Office',
    icon: 'mdi:desk',
    temperature: 'sensor.office_climate_temperature',
    humidity: 'sensor.office_climate_humidity',
    window: 'binary_sensor.office_window',
    lights: {
      group: 'light.office_lights',
      color: true,
      members: [
        {
          group: 'light.office_top',
          members: [
            'light.office_top_1',
            'light.office_top_2',
            'light.office_top_3',
            'light.office_top_4',
            'light.office_top_5',
            'light.office_top_6',
          ],
        },
      ],
      scenes: [
        'scene.office_lights_adrift',
        'scene.office_lights_arctic_aurora',
        'scene.office_lights_chinatown',
        'scene.office_lights_concentrate',
        'scene.office_lights_disturbia',
        'scene.office_lights_emerald_flutter',
        'scene.office_lights_energize',
        'scene.office_lights_lake_placid',
        'scene.office_lights_motown',
        'scene.office_lights_natural_light',
        'scene.office_lights_nebula',
        'scene.office_lights_nightlight',
        'scene.office_lights_osaka',
        'scene.office_lights_read',
        'scene.office_lights_relax',
        'scene.office_lights_rest',
        'scene.office_lights_soho',
        'scene.office_lights_tokyo',
      ],
      activeScene: 'select.office_lights_scene',
    },
    heating: {
      entity: 'climate.office_heating',
      preset: true,
      thermostats: [
        {
          valve: 'sensor.office_thermostat_valve_position',
          battery: 'sensor.office_thermostat_battery',
        },
      ],
    },
    printer3d: {
      entity: 'sensor.office_3d_printer',
      progress: 'sensor.office_3d_printer_progress',
      filename: 'sensor.office_3d_printer_filename',
      material: 'sensor.office_3d_printer_material',
      speed: 'sensor.office_3d_printer_print_speed',
      start: 'sensor.office_3d_printer_print_start',
      finish: 'sensor.office_3d_printer_print_finish',
      nozzle: {
        temperature: 'sensor.office_3d_printer_nozzle_temperature',
        target: 'sensor.office_3d_printer_nozzle_target_temperature',
      },
      bed: {
        temperature: 'sensor.office_3d_printer_heatbed_temperature',
        target: 'sensor.office_3d_printer_heatbed_target_temperature',
      },
      camera: 'camera.office_3d_printer_camera',
      actions: {
        pause: 'button.office_3d_printer_pause_job',
        resume: 'button.office_3d_printer_resume_job',
        continue: 'button.office_3d_printer_continue_job',
        cancel: 'button.office_3d_printer_cancel_job',
      },
      outlet: {
        entity: 'switch.office_3d_printer_outlet',
        energy: {
          power: 'sensor.office_3d_printer_outlet_power',
          today: 'sensor.office_3d_printer_outlet_energy_daily',
          total: 'sensor.office_3d_printer_outlet_energy',
        },
      },
    },
    diffuser: {
      entity: 'switch.office_perfume_diffuser',
      amount: 'number.office_perfume_diffuser_amount',
    },
    batteries: [
      'sensor.office_button_1_battery',
      'sensor.office_button_2_battery',
      'sensor.office_button_3_battery',
      'sensor.office_climate_battery',
      'sensor.office_switch_battery',
      'sensor.office_window_battery',
    ],
    firmware: [
      'update.office_3d_printer_outlet_firmware',
      'update.office_climate_firmware',
      'update.office_thermostat_firmware',
      'update.office_window_firmware',
    ],
  },
  {
    key: 'toilet',
    name: 'Toilet',
    icon: 'mdi:toilet',
    temperature: 'sensor.toilet_climate_temperature',
    humidity: 'sensor.toilet_climate_humidity',
    lights: {
      group: 'light.toilet_lights',
      members: ['light.toilet_top'],
      scenes: [
        'scene.toilet_lights_concentrate',
        'scene.toilet_lights_energize',
        'scene.toilet_lights_natural_light',
        'scene.toilet_lights_nightlight',
        'scene.toilet_lights_read',
        'scene.toilet_lights_relax',
        'scene.toilet_lights_rest',
      ],
      activeScene: 'select.toilet_lights_scene',
    },
    heating: {
      entity: 'climate.toilet_heating',
      preset: true,
      thermostats: [
        {
          valve: 'sensor.toilet_thermostat_valve_position',
          battery: 'sensor.toilet_thermostat_battery',
        },
      ],
    },
    batteries: ['sensor.toilet_climate_battery', 'sensor.toilet_switch_battery'],
    firmware: ['update.toilet_climate_firmware', 'update.toilet_thermostat_firmware'],
  },
];

const CARS: readonly Car[] = [
  {
    key: 'sedan',
    icon: 'mdi:car-sports',
    metadata: 'sensor.garage_sedan_metadata',
    fuel: 'sensor.garage_sedan_fuel',
    range: 'sensor.garage_sedan_range',
    mileage: 'sensor.garage_sedan_mileage',
    lock: 'sensor.garage_sedan_doors',
    alarm: 'sensor.garage_sedan_alarm',
    alarmActive: 'binary_sensor.garage_sedan_alarm_active',
    doors: [
      'binary_sensor.garage_sedan_door_front_left',
      'binary_sensor.garage_sedan_door_front_right',
      'binary_sensor.garage_sedan_door_rear_left',
      'binary_sensor.garage_sedan_door_rear_right',
    ],
    hood: 'binary_sensor.garage_sedan_hood',
    tailgate: 'binary_sensor.garage_sedan_tailgate',
    windows: [
      'sensor.garage_sedan_window_front_left',
      'sensor.garage_sedan_window_front_right',
      'sensor.garage_sedan_window_rear_left',
      'sensor.garage_sedan_window_rear_right',
    ],
    tyres: [
      'sensor.garage_sedan_tyre_pressure_front_left',
      'sensor.garage_sedan_tyre_pressure_front_right',
      'sensor.garage_sedan_tyre_pressure_rear_left',
      'sensor.garage_sedan_tyre_pressure_rear_right',
    ],
    tyreTargets: [
      'sensor.garage_sedan_tyre_pressure_target_front_left',
      'sensor.garage_sedan_tyre_pressure_target_front_right',
      'sensor.garage_sedan_tyre_pressure_target_rear_left',
      'sensor.garage_sedan_tyre_pressure_target_rear_right',
    ],
    location: 'device_tracker.garage_sedan_location',
  },
  {
    key: 'suv',
    icon: 'mdi:car-estate',
    metadata: 'sensor.garage_suv_metadata',
    fuel: 'sensor.garage_suv_fuel',
    range: 'sensor.garage_suv_range',
    mileage: 'sensor.garage_suv_mileage',
    lock: 'sensor.garage_suv_doors',
    alarm: 'sensor.garage_suv_alarm',
    alarmActive: 'binary_sensor.garage_suv_alarm_active',
    doors: [
      'binary_sensor.garage_suv_door_front_left',
      'binary_sensor.garage_suv_door_front_right',
      'binary_sensor.garage_suv_door_rear_left',
      'binary_sensor.garage_suv_door_rear_right',
    ],
    hood: 'binary_sensor.garage_suv_hood',
    tailgate: 'binary_sensor.garage_suv_tailgate',
    windows: [
      'sensor.garage_suv_window_front_left',
      'sensor.garage_suv_window_front_right',
      'sensor.garage_suv_window_rear_left',
      'sensor.garage_suv_window_rear_right',
    ],
    sunroof: 'sensor.garage_suv_sunroof',
    tyres: [
      'sensor.garage_suv_tyre_pressure_front_left',
      'sensor.garage_suv_tyre_pressure_front_right',
      'sensor.garage_suv_tyre_pressure_rear_left',
      'sensor.garage_suv_tyre_pressure_rear_right',
    ],
    tyreTargets: [
      'sensor.garage_suv_tyre_pressure_target_front_left',
      'sensor.garage_suv_tyre_pressure_target_front_right',
      'sensor.garage_suv_tyre_pressure_target_rear_left',
      'sensor.garage_suv_tyre_pressure_target_rear_right',
    ],
    location: 'device_tracker.garage_suv_location',
  },
];

export const DEMO: Home = {
  title: 'Home',
  sections: SECTION_TITLES,
  popupOpen: { tablet: 'unfold', desktop: 'unfold' },
  outside: OUTSIDE,
  vacation: VACATION,
  rooms: ROOMS,
  people: PEOPLE,
  cars: CARS,
  system: SYSTEM,
};
